#!/bin/bash

sudo apt-get update

# Docker can be installed on linux kernal version 3.8 or above
# Check linux kernal version: uname -a
# Install required package: 
sudo apt-get install apt-transport-https ca-certificates -y

echo -n "downloading key..."
# Download GPG key: 
curl -fsSL https://download.docker.com/linux/ubuntu/gpg |sudo apt-key add -
echo "done"

echo -n "system updating...."
sudo apt-get update -y
echo "done"

echo -n "Installing docker..."
sudo snap install docker     # version 18.06.1-ce

echo "done"

echo -n "setting /snap/bin in $PATH"
export PATH="/snap/bin/:$PATH"
echo "done"
